

HEATER_DID = "C1"
HEATER_PROTOCOL = "X10"
HEATER_API = "http://localhost:8000"
HEATER_USERNAME = "raton"
HEATER_PASSWORD = "soportep"
HEATER_MARGIN = 0.5
HEATER_INCREMENT = 0.5

INTERNAL_TEMPERATURE_URI = "http://raspberry/rest/temperature"
